---
name: Release Charts

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: helm-chart-publish-${{ github.repository }}
  cancel-in-progress: true 

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Create Helm Chart Package
        run: |
          mkdir -p docs
          helm lint charts
          helm package charts -d docs
          helm repo index docs --url "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"

      - name: Configure Git for Pages
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Publish to GitHub Pages
        run: |
          git checkout -b gh-pages || git switch gh-pages
          mv docs/* .
          git add .
          git commit -m "Update Helm Chart at $(date)"
          git push origin gh-pages
